In [1]:
import pandas as pd
import numpy as np

##### Чтение и анализ файлов

In [2]:
markup  = pd.read_excel('.../Тестовое_задание_Data_аналитик_ЦО_2025_2.xlsx',
                       sheet_name = 'Справочник наценок')

In [3]:
markup = markup[markup['Активный'] == 'Да']

In [4]:
markup.head(3)

,Сегмент рынка,Категория,Бренд,Продукт,Дата начала,Дата окончания,Наценка,Активный
0,Люкс,NaN,NaN,NaN,2025-01-01,NaT,1.2,Да
1,Массмаркет,NaN,NaN,NaN,2025-01-01,NaT,0.7,Да
2,Люкс,Макияж,NaN,NaN,2025-01-01,NaT,0.9,Да

In [5]:
markup_null = markup[markup['Дата окончания'] == 'NaT']

In [6]:
markup_null.head()

Empty DataFrame
Columns: [Сегмент рынка, Категория, Бренд, Продукт, Дата начала, Дата окончания, Наценка, Активный]
Index: []

In [7]:
list_product = pd.read_excel('.../Тестовое_задание_Data_аналитик_ЦО_2025_2.xlsx',
                             sheet_name = 'Данные для задачи 1')

In [8]:
list_product.head(3)

,Бренд,Код товара,Наименование товара,Категория1,Категория2,Категория3,Категория4,Сегмент,Цена закупки товара,letu.ru,iledebeaute.ru,rivegauche.ru,Ozon,Wildberries,MagnitMarket,Megamarket,lamoda.ru,tsum.ru,visagehall.ru
0,Clarins,19000412437,CLARINS Тушь д/ресниц Wonder volume xxl 8мл,Макияж,Глаза,Тушь для ресниц,NaN,Люкс,983,NaN,1029.0,NaN,NaN,NaN,NaN,NaN,1117.0,NaN,NaN
1,Clarins,14037100013,Clarins Флюид тональный устойчивый с омолажива...,Макияж,Лицо,Тональные основы,Жидкие тональные основы,Люкс,1957,NaN,2107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Clarins,19000033387,CLARINS Масло-блеск для губ Lip Comfort Oil т....,Макияж,Губы,Масло для губ_макияж,NaN,Люкс,850,NaN,1065.0,919.0,964.0,NaN,NaN,NaN,924.0,1574.0,964.0

In [9]:
sorted(list_product['Категория3'].dropna().unique())

['Авто загар',
 'Адвент-календарь',
 'Аксессуары',
 'Антицеллюлитная серия/коррекция фигуры',
 'Бальзам для губ_макияж',
 'Блеск для губ',
 'Бронзер',
 'ВВ/СС средства',
 'Гель для бровей',
 'Дезодорант',
 'Для бритья',
 'Для ванны и душа',
 'Карандаш для бровей',
 'Карандаш для глаз',
 'Карандаш для губ',
 'Кисти',
 'Контуринг',
 'Корректор/консилер',
 'Крем для ног',
 'Крем для рук',
 'Крем для тела',
 'Маркеры для бровей',
 'Масла',
 'Масло для губ_макияж',
 'Матирующие салфетки',
 'Молочко для тела',
 'Набор для макияжа лица',
 'Набор для макияжа_прочее',
 'Основной уход',
 'Очищение/демакияж',
 'Палетки_глаза',
 'Палетки_лицо',
 'Пилинг/скраб для лица',
 'Плампер для губ',
 'Подарочные наборы_уход',
 'Подводки',
 'Помада для губ',
 'После бритья',
 'После загара',
 'Праймер/база_лицо',
 'Прочее_тело',
 'Пудра_лицо',
 'Румяна',
 'Скраб-пилинг для тела',
 'Солнцезащитные средства',
 'Специальный уход',
 'Средства для век',
 'Сыворотки',
 'Тени для век',
 'Тинт/пигмент',
 'Тональные основы',
 'Тоники-лосьоны-тонеры',
 'Тушь для бровей',
 'Тушь для ресниц',
 'Уход для бровей',
 'Уход за губами',
 'Уход за лицом _маски',
 'Фиксаторы макияжа',
 'Хайлайтер/люминайзер',
 'Шампунь']

In [10]:
eror_product = list_product[list_product['Категория3'].str.contains('_', na=False)]

In [11]:
eror_product.head(3)

,Бренд,Код товара,Наименование товара,Категория1,Категория2,Категория3,Категория4,Сегмент,Цена закупки товара,letu.ru,iledebeaute.ru,rivegauche.ru,Ozon,Wildberries,MagnitMarket,Megamarket,lamoda.ru,tsum.ru,visagehall.ru
2,Clarins,19000033387,CLARINS Масло-блеск для губ Lip Comfort Oil т....,Макияж,Губы,Масло для губ_макияж,NaN,Люкс,850,NaN,1065.0,919.0,964.0,NaN,NaN,NaN,924.0,1574.0,964.0
4,Clarins,19000168458,Clarins Масло-блеск д/губ Lip Comfort 17 7мл,Макияж,Губы,Масло для губ_макияж,NaN,Люкс,835,NaN,924.0,1039.0,1045.0,NaN,NaN,NaN,1065.0,1742.0,NaN
5,Clarins,19000430971,CLARINS Масло-блеск д/губ 54 7мл,Макияж,Губы,Масло для губ_макияж,NaN,Люкс,898,NaN,NaN,999.0,1065.0,NaN,NaN,NaN,NaN,NaN,1085.0

NB! При анализе данных натолкнулся на возможную ошибку, очень странно что в "Категория3" содержатся наименования по типу "Масло для губ_макияж" сложилось впечатление что это ошибка, т.к. Макияж это одно из возможных наименований "Категории1". Так как нет возможности изучить первоисточник информации и возможную причину такой строки, то игнорируем данный факт.

##### Привязка наценки и расчет цены

NB! Предоставленное решение задачи по проставлению наценки выполняется за время O(n*k), при n == k время решения будет O(n^2). В настощее время я изучаю алгоритмы, поэтому вопрос о решении данной задачи за время O(n) возник сразу. Погуглив и пообщавшись с gpt выяснил, что эту задачу можно попробовать решить с помощью алгоритма DFS поиска в глубину. Увы до данной темы в обучении я ещё не дошёл, поэтому не стал использовать ИИшный код без его понимания и возможности изменить и прокомментировать.

In [12]:
def find_markup(row, markup):
    # Продукт
    if not markup[markup['Продукт'] == row['Код товара']].empty:
        return markup[markup['Продукт'] == row['Код товара']].iloc[0]['Наценка'], 1

    # 2 Бренд/Категория3
    if not markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория3']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория3']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 2

    # 3 Бренд/Категория2
    if not markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория2']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория2']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 3

    # 4 Бренд/Категория1
    if not markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория1']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'] == row['Категория1']) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 4

    # 5 Бренд
    if not markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'].isna()) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Бренд'] == row['Бренд']) & (markup['Категория'].isna()) & (markup['Сегмент рынка'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 5

    # 6
    if not markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория3']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория3']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 6

    # 7
    if not markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория2']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория2']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 7

    # 8
    if not markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория1']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'] == row['Категория1']) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 8

    # 9
    if not markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'].isna()) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].empty:
        return markup[(markup['Сегмент рынка'] == row['Сегмент']) & (markup['Категория'].isna()) & (markup['Бренд'].isna()) & (markup['Продукт'].isna())].iloc[0]['Наценка'], 9

    # nan если ничего выше
    return np.nan, 99

In [13]:
# запуск функции выше
results = list_product.apply(lambda row: find_markup(row, markup), axis=1)

In [14]:
# проставляем наценку и группу присвоения наценки
list_product['Наценка'] = [res[0] for res in results]
list_product['cur_priority'] = [res[1] for res in results]

In [15]:
list_product = list_product[list_product['Наценка'].notna()]

In [16]:
# проверка есть ли позици по которым наценка не притянулась

test_markup = list_product[list_product['Наценка'].isna()]

print(len(test_markup))

0

In [17]:
list_product['Розничная_цена'] = round(list_product['Цена закупки товара'] * (list_product['Наценка'] + 1), 2)

In [18]:
list_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Бренд                683 non-null    object
 1   Код товара           683 non-null    int64
 2   Наименование товара  683 non-null    object
 3   Категория1           683 non-null    object
 4   Категория2           683 non-null    object
 5   Категория3           683 non-null    object
 6   Категория4           297 non-null    object
 7   Сегмент              683 non-null    object
 8   Цена закупки товара  683 non-null    int64
 9   letu.ru              193 non-null    float64
 10  iledebeaute.ru       495 non-null    float64
 11  rivegauche.ru        610 non-null    float64
 12  Ozon                 471 non-null    float64
 13  Wildberries          176 non-null    float64
 14  MagnitMarket         120 non-null    float64
 15  Megamarket           89 non-null     float64
 16  lamoda.ru            364 non-null    float64
 17  tsum.ru              226 non-null    float64
 18  visagehall.ru        388 non-null    float64
 19  Наценка              683 non-null    float64
 20  cur_priority         683 non-null    int64
 21  Розничная_цена       683 non-null    float64
dtypes: float64(12), int64(3), object(7)
memory usage: 117.5+ KB

##### Подготовка df

In [20]:
firms = ['letu.ru',
         'iledebeaute.ru',
         'rivegauche.ru',
         'Ozon',
         'Wildberries',
         'MagnitMarket',
         'Megamarket',
         'lamoda.ru',
         'tsum.ru',
         'visagehall.ru'
]

In [21]:
list_product['Мин_цена_конкурента'] = list_product[firms].min(axis=1)

In [22]:
list_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Бренд                683 non-null    object
 1   Код товара           683 non-null    int64
 2   Наименование товара  683 non-null    object
 3   Категория1           683 non-null    object
 4   Категория2           683 non-null    object
 5   Категория3           683 non-null    object
 6   Категория4           297 non-null    object
 7   Сегмент              683 non-null    object
 8   Цена закупки товара  683 non-null    int64
 9   letu.ru              193 non-null    float64
 10  iledebeaute.ru       495 non-null    float64
 11  rivegauche.ru        610 non-null    float64
 12  Ozon                 471 non-null    float64
 13  Wildberries          176 non-null    float64
 14  MagnitMarket         120 non-null    float64
 15  Megamarket           89 non-null     float64
 16  lamoda.ru            364 non-null    float64
 17  tsum.ru              226 non-null    float64
 18  visagehall.ru        388 non-null    float64
 19  Наценка              683 non-null    float64
 20  cur_priority         683 non-null    int64
 21  Розничная_цена       683 non-null    float64
 22  Мин_цена_конкурента  683 non-null    float64
dtypes: float64(13), int64(3), object(7)
memory usage: 122.9+ KB

In [23]:
analysis_preces = list_product[['Бренд', 
                                'Код товара', 
                                'Наименование товара',
                                'Категория1',
                                'Категория2',
                                'Категория3',
                                'Категория4',
                                'Сегмент',
                                'Цена закупки товара', 
                                'Наценка', 
                                'Розничная_цена', 
                                'Мин_цена_конкурента',
                                'cur_priority']].copy()

In [24]:
analysis_preces['diff'] = analysis_preces['Розничная_цена'] - analysis_preces['Мин_цена_конкурента']

In [25]:
analysis_preces.head(2)

,Бренд,Код товара,Наименование товара,Категория1,Категория2,Категория3,Категория4,Сегмент,Цена закупки товара,Наценка,Розничная_цена,Мин_цена_конкурента,cur_priority,diff
0,Clarins,19000412437,CLARINS Тушь д/ресниц Wonder volume xxl 8мл,Макияж,Глаза,Тушь для ресниц,NaN,Люкс,983,1.03,1995.49,1029.0,5,966.49
1,Clarins,14037100013,Clarins Флюид тональный устойчивый с омолажива...,Макияж,Лицо,Тональные основы,Жидкие тональные основы,Люкс,1957,1.03,3972.71,2107.0,5,1865.71

In [28]:
# группы приоритета проставления наценки
analysis_preces['cur_priority'].dropna().unique()

array([5, 2, 3, 1])

##### Сравнительный анализ цен

Есть два основных подхода:<br>1. Для каждой номенклатуры присвоить собственный уровень наценки, данный подход позволит гибко придерживаться стратегии компании, но в тоже время не занижать цены по товарам которые и так ниже чем у конкурентов.<br>2. Наценка регулируется для группы товаров, при такой схеме возможна ситуация, что из-за товара с высокой себестоимостью придется сильно снижать маржинальность остальных товаров в этой группе. Для тестовой задачи разделим популяцию, выберем две группы для предложения внесения изменения наценки в справочник. По остальным товаром возьмем минимальную цену конкурентов и проверим, что наценка не ниже 10%.

In [29]:
#возьмем группу где наценка на весь бренд (5)

analysis_5 = analysis_preces[(analysis_preces['cur_priority'] == 5) & (analysis_preces['Бренд'] == 'Clarins')].copy()

#текущая наценка на бренд 103%
analysis_5['new_markup'] = 0.1
analysis_5['new_price'] = analysis_5['Цена закупки товара'] * (analysis_5['new_markup'] + 1)


analysis_5_false = analysis_5[analysis_5['new_price'] > analysis_5['Мин_цена_конкурента']]

analysis_5_false.head(2)

,Бренд,Код товара,Наименование товара,Категория1,Категория2,Категория3,Категория4,Сегмент,Цена закупки товара,Наценка,Розничная_цена,Мин_цена_конкурента,cur_priority,diff,new_markup,new_price
0,Clarins,19000412437,CLARINS Тушь д/ресниц Wonder volume xxl 8мл,Макияж,Глаза,Тушь для ресниц,NaN,Люкс,983,1.03,1995.49,1029.0,5,966.49,0.1,1081.3
1,Clarins,14037100013,Clarins Флюид тональный устойчивый с омолажива...,Макияж,Лицо,Тональные основы,Жидкие тональные основы,Люкс,1957,1.03,3972.71,2107.0,5,1865.71,0.1,2152.7

NB! Как было сказано выше из-за того что группа на которую действует одна наценка очень большая и разнородная. Невозможно применить одну наценку на все товары чтобы удовлетворить условия (цена ниже конкурентов и наценка выше 10%)

In [30]:
#наценка на бренд и категория 3

analysis_2 = analysis_preces[(analysis_preces['cur_priority'] == 2) &
                            (analysis_preces['Бренд'] == 'Clarins') &
                            (analysis_preces['Категория3'] == 'Крем для тела')
].copy()

#текущая наценка на бренд и категорию 3 106%
analysis_2['new_markup'] = 0.35
analysis_2['new_price'] = analysis_2['Цена закупки товара'] * (analysis_2['new_markup'] + 1)


analysis_2_false = analysis_2[analysis_2['new_price'] > analysis_2['Мин_цена_конкурента']]

analysis_2_false.head(2)

Empty DataFrame
Columns: [Бренд, Код товара, Наименование товара, Категория1, Категория2, Категория3, Категория4, Сегмент, Цена закупки товара, Наценка, Розничная_цена, Мин_цена_конкурента, cur_priority, diff, new_markup, new_price]
Index: []

Для того чтобы следовать стретегии компании необходимо в справочник наценок внести новую наценку по бренду Clarins и категории3 'Крем для тела'.
Однако при таком способе регулировании мы теряем маржинальность у товаров чья цена первонаально уже была ниже чем у конкуретов.

In [31]:
#Для всех остальных товаров сделаем индивидуальную наценку

analysis_other = analysis_preces[(~analysis_preces['Код товара'].isin(analysis_2['Код товара'])) &
                                    (analysis_preces['diff'] > 100)].copy()


analysis_other['new_price'] = analysis_other['Мин_цена_конкурента']
analysis_other['new_markup'] = (analysis_other['new_price'] - analysis_other['Цена закупки товара'])/analysis_other['Цена закупки товара']

In [33]:
# товары по которым невозможно выполнить условия самой низкой цены в рынке и наценки не менее 10% 

analysis_error = analysis_other[analysis_other['new_markup'] < 0.1]
print(f'Кол-во товаров с невозможностью выполнения сразу двух условий: {len(analysis_error)}')
analysis_error.head(2)

Кол-во товаров с невозможностью выполнения сразу двух условий: 124

,Бренд,Код товара,Наименование товара,Категория1,Категория2,Категория3,Категория4,Сегмент,Цена закупки товара,Наценка,Розничная_цена,Мин_цена_конкурента,cur_priority,diff,new_price,new_markup
0,Clarins,19000412437,CLARINS Тушь д/ресниц Wonder volume xxl 8мл,Макияж,Глаза,Тушь для ресниц,NaN,Люкс,983,1.03,1995.49,1029.0,5,966.49,1029.0,0.046796
1,Clarins,14037100013,Clarins Флюид тональный устойчивый с омолажива...,Макияж,Лицо,Тональные основы,Жидкие тональные основы,Люкс,1957,1.03,3972.71,2107.0,5,1865.71,2107.0,0.076648

##### Индекс цен

In [34]:
firms = ['letu.ru',
         'iledebeaute.ru',
         'rivegauche.ru',
         'Ozon',
         'Wildberries',
         'MagnitMarket',
         'Megamarket',
         'lamoda.ru',
         'tsum.ru',
         'visagehall.ru'
]

In [35]:
index_price = (list_product[firms].div(list_product['Розничная_цена'], axis=0)) * 100

average_index = index_price.mean()

print("Средний индекс цен по конкурентам (в %):")
print(average_index)

Средний индекс цен по конкурентам (в %):
letu.ru           87.945552
iledebeaute.ru    83.419823
rivegauche.ru     83.373170
Ozon              81.227571
Wildberries       82.449935
MagnitMarket      85.464525
Megamarket        88.644373
lamoda.ru         84.101661
tsum.ru           99.890483
visagehall.ru     82.986918
dtype: float64

NB! Согласно ценовому индексу средних цен, можно сделать вывод о том, что у всех конкурентов цены ниже. С конкурентом tsum.ru цены на одном уровне

##### Вывод

После выполнения задания можно прийти к следующим выводам:<br>1. Есть позиции по которым невозможно выполнить одновременно два условия, в df analysis_error 124 товара по которым при установлении минимальной цены в рынке мы не можем установить наценку 10 и более %. Возможно конкуренты распродают остатки по почти закупочным ценам либо у них ниже цена закупки.<br>2. Если регулировать наценку справочником по группе товаров и данная группа будет содержать большой перечень товаров (например наценка на весь бренд), то при таком регулировании возможно неоправданное снижение наценки по тем товарам по которым она уже является самой низкой среди конкурентов